theme: minima
title: 自作OS×自作ブラウザで学ぶ Webページが表示されるまで サポートページ
show_excerpts: false
minima:
  social_links:
    twitter:
    - id: hikalium
    - id: d0iasm
    github:
    - id: hikalium
    - id: d0iasm
    youtube_channel: UCMsstGhINXdpMqo9tsElCMQ
    youtube_channel_name: 低レイヤーガール
