theme: minima
title: 自作OS×自作ブラウザで学ぶ Webページが表示されるまで サポートページ
show_excerpts: false
minima:
  social_links:
    twitter: hikalium
    twitter: d0iasm
    github: hikalium
    github: d0iasm
    youtube: 低レイヤーガール
    youtube_channel: UCMsstGhINXdpMqo9tsElCMQ
    youtube_channel_name: 低レイヤーガール
